// <auto-generated />
using System;
using AzureDevOpsToPowerBI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureDevOpsToPowerBI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519211818_ConvertDecimalToDouble")]
    partial class ConvertDecimalToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.Area", b =>
                {
                    b.Property<string>("ProjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaSK")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "AreaSK");

                    b.Property<string>("AreaId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "AreaId");

                    b.Property<string>("AreaPath")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "AreaPath");

                    b.HasKey("ProjectKey", "AreaSK");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.Bug", b =>
                {
                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaSK")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Custom_BugType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Custom_TicketID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Custom_TicketPriority")
                        .HasColumnType("TEXT");

                    b.Property<string>("IterationSK")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentWorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkItemId", "ProjectKey");

                    b.ToTable("Bugs", (string)null);
                });

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.Iteration", b =>
                {
                    b.Property<string>("ProjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("IterationSK")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "IterationSK");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "EndDate");

                    b.Property<string>("IterationName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "IterationName");

                    b.Property<string>("IterationPath")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "IterationPath");

                    b.Property<double?>("SprintHoursCapacity")
                        .HasColumnType("REAL");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "StartDate");

                    b.HasKey("ProjectKey", "IterationSK");

                    b.ToTable("Iterations", (string)null);
                });

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.ProjectProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaSK")
                        .HasColumnType("TEXT");

                    b.Property<string>("IterationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IterationSK")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectEffort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectRealEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Velocity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProjectProfiles", (string)null);
                });

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.SprintCapacity", b =>
                {
                    b.Property<string>("ProjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("IterationSK")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "IterationSK");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ProjectName");

                    b.Property<double?>("SprintHoursCapacity")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "SprintHoursCapacity");

                    b.Property<string>("SprintName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "SprintName");

                    b.Property<string>("SprintPath")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "SprintPath");

                    b.HasKey("ProjectKey", "IterationSK");

                    b.ToTable("SprintCapacities", (string)null);
                });

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.TfsTask", b =>
                {
                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaSK")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CompletedWork")
                        .HasColumnType("REAL");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IterationSK")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OriginalEstimate")
                        .HasColumnType("REAL");

                    b.Property<int?>("ParentWorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkItemId", "ProjectKey");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("AzureDevOpsToPowerBI.Models.Entities.UserStory", b =>
                {
                    b.Property<int>("WorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaSK")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CycleTimeDays")
                        .HasColumnType("REAL");

                    b.Property<string>("IterationSK")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LeadTimeDays")
                        .HasColumnType("REAL");

                    b.Property<int?>("ParentWorkItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StoryPoints")
                        .HasColumnType("REAL");

                    b.Property<string>("TagNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkItemId", "ProjectKey");

                    b.ToTable("UserStories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
